version: '3.8'

services:
  pdf-ocr-app:
    build: .
    container_name: pdf-ocr-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - pdf_uploads:/tmp/pdf_uploads
      - pdf_outputs:/tmp/pdf_outputs
    restart: unless-stopped
    networks:
      - pdf-ocr-network

volumes:
  pdf_uploads:
  pdf_outputs:

networks:
  pdf-ocr-network:
    driver: bridge
